name = "Path of Exile Filter"
grammar = "filter"
path_suffixes = ["filter"]
line_comments = ["# "]
brackets = [
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
]
hard_tabs = true
